name: practices
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.8
  blur: ^3.1.0
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  givestarreviews: ^1.0.2
  go_router: ^12.1.0
  mockito: ^5.4.3
  test: ^1.24.9

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
